import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/container/header/Header";
import Footer from "@/components/container/footer/footer";
import { ReduxProvider } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-300`}
      >
        <ReduxProvider>
        <div className="wrapper flex flex-col justify-center">
          <Header/>
        {children}
        <Footer/>
        </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
