import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/container/header/Header';
import Footer from '@/components/container/footer/footer';
import { ReduxProvider } from './providers';
import Script from 'next/script';
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <Script
          src='https://checkout.razorpay.com/v1/checkout.js'
          strategy='beforeInteractive'
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-200 flex flex-col items-center`}
      >
        <ReduxProvider>
          <Toaster position='top-right' />
          <div className='wrapper mx-auto w-full'>
            <Header />
            {children}
            <Footer />
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
